In [10]:
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np

In [11]:
#import dataset
df = pd.read_csv('response indo.csv')
df

Age (umur) Occupation (Pekerjaan)  Music  Slow songs or fast songs  Dance  \
0           19              Mahasiswa      3                         3      1   
1           19              Mahasiswa      5                         3      5   
2           20              Mahasiswa      5                         2      1   
3           19              Mahasiswa      5                         2      3   
4           19              Mahasiswa      5                         3      4   
..         ...                    ...    ...                       ...    ...   
70          20              Mahasiswa      5                         3      4   
71          20              Mahasiswa      5                         3      2   
72          20              Mahasiswa      4                         4      2   
73          21              Mahasiswa      5                         3      5   
74          19              Mahasiswa      5                         3      4   

    Folk  Country  Classical music  Musical  Pop  ...  Reggae, Ska  \
0      1        1                1        4    5  ...            1   
1      4        4                4        5    4  ...            4   
2      2        1                5        5    4  ...            1   
3      3        4                4        4    4  ...            2   
4      4        3                3        3    4  ...            3   
..   ...      ...              ...      ...  ...  ...          ...   
70     3        4                2        3    4  ...            1   
71     2        3                2        3    5  ...            3   
72     1        1                3        2    4  ...            1   
73     3        3                3        3    4  ...            3   
74     2        2                3        3    4  ...            1   

    Swing, Jazz  Rock n roll  Alternative  Latino  Techno, Trance  Opera  \
0             4            1            1       1               1      1   
1             5            5            5       4               5      4   
2             3            1            1       1               1      3   
3             5            3            3       4               3      3   
4             4            3            3       3               3      3   
..          ...          ...          ...     ...             ...    ...   
70            3            3            2       1               1      2   
71            4            3            3       4               4      4   
72            5            1            2       1               5      1   
73            3            3            5       2               4      2   
74            2            3            4       1               2      2   

           Smoking         Alcohol  Healthy eating  
0     never smoked           never               2  
1   current smoker           never               2  
2     never smoked  social drinker               5  
3     never smoked           never               4  
4     never smoked           never               4  
..             ...             ...             ...  
70    never smoked  social drinker               3  
71    never smoked           never               3  
72    never smoked  social drinker               4  
73    never smoked  social drinker               1  
74    never smoked  social drinker               3  

[75 rows x 24 columns]

In [12]:
#mengubah string menjadi angka di Smoking  
df["Smoking"] = df["Smoking"].replace('current smoker', 3)  
df["Smoking"] = df["Smoking"].replace('former smoker', 2) 
df["Smoking"] = df["Smoking"].replace('tried smoking', 1)   
df["Smoking"] = df["Smoking"].replace('never smoked', 0)
#mengubah string menjadi angka di Alcohol
df["Alcohol"] = df["Alcohol"].replace('drink a lot', 2)  
df["Alcohol"] = df["Alcohol"].replace('social drinker', 1)    
df["Alcohol"] = df["Alcohol"].replace('never', 0)

In [13]:
#drop data
newDf = df.dropna()
print(newDf.isna().values.any())

False


In [14]:
#declare feature dan target
feature = newDf[["Music","Slow songs or fast songs","Dance","Folk","Country","Classical music","Musical","Pop","Rock","Metal or Hardrock","Punk","Hiphop, Rap","Reggae, Ska","Swing, Jazz","Rock n roll","Alternative","Latino","Techno, Trance","Opera"]]
target = newDf[["Smoking","Alcohol","Healthy eating"]]

In [17]:
from sklearn.linear_model import LinearRegression
x, y = np.array(feature), np.array(target)

In [18]:
#mengapply linear regression dan fit
model = LinearRegression().fit(x, y)

In [19]:
r_sq = model.score(x, y)
print('coefficient of determination:', r_sq)# hasil R-Squared (bila di bawah 0.5 maka feature tidak berpengaruh kepada target)
print('intercept:', model.intercept_)# hasil coefficient pada b0 (bila di atas 0.05 maka feature tidak berpengaruh kepada target)
print('slope:', model.coef_)# hasil coefficient pada bias setelah b0 yakni b1 b2 b3(bila di atas 0.05 maka feature tidak berpengaruh kepada target)

coefficient of determination: 0.25462993810589
intercept: [-0.1049353   0.54798976  1.34878076]
slope: [[-0.24203701  0.06666012 -0.12241315  0.07216439  0.02871775  0.10085446
   0.00277247  0.02422173  0.0569197   0.05889235 -0.04694674  0.10073666
   0.05387589  0.0129651   0.10599831  0.15403392 -0.16766027 -0.02788561
   0.01928874]
 [ 0.16250622 -0.07199688 -0.11183086 -0.09898572 -0.11816168 -0.11821318
   0.07680708 -0.04414884  0.14604851 -0.28906435  0.12289637 -0.01709104
   0.00860719  0.02349297  0.14939571  0.02346773 -0.03480531  0.04671162
   0.02467975]
 [ 0.48056602  0.26237031 -0.136246    0.01755553 -0.11414822 -0.10770069
   0.30511918 -0.016153   -0.27238222  0.08162894  0.04657326 -0.04724924
  -0.14124375  0.02503882  0.11084119 -0.08993002  0.06844524  0.05423198
  -0.16320764]]


C:\Users\Albert\Anaconda3\lib\site-packages\sklearn\base.py:420: FutureWarning: The default value of multioutput (not exposed in score method) will change from 'variance_weighted' to 'uniform_average' in 0.23 to keep consistent with 'metrics.r2_score'. To specify the default value manually and avoid the warning, please either call 'metrics.r2_score' directly or make a custom scorer with 'metrics.make_scorer' (the built-in scorer 'r2' uses multioutput='uniform_average').
  "multioutput='uniform_average').", FutureWarning)


In [20]:
y_pred = model.predict(x)
print('predicted response:', y_pred, sep='\n')
#menghasilkan prediksi prediksi target dengan linear regression

predicted response:
[[ 2.41779359e-01  6.82355450e-01  3.98287740e+00]
 [ 9.33022576e-01  3.51691465e-01  3.05446790e+00]
 [-1.31419440e-01  7.05621864e-01  4.37995773e+00]
 [-1.00978695e-02  4.05921268e-01  3.61093552e+00]
 [ 2.52141850e-01  2.65384622e-01  3.24518802e+00]
 [ 1.00035320e-01  3.94205951e-01  3.04517255e+00]
 [ 1.46223517e-01  4.28305066e-01  1.71289046e+00]
 [-9.92335506e-02  6.02963637e-01  3.45901826e+00]
 [ 1.56706835e-01  5.85068369e-01  2.59545903e+00]
 [ 3.68103525e-01  1.02473776e+00  3.15402330e+00]
 [-5.88063212e-02  3.01401966e-01  4.00975578e+00]
 [ 1.46788435e-03  4.85286809e-01  3.95590818e+00]
 [-2.96205762e-01  5.74392348e-01  3.40314063e+00]
 [ 1.74963314e-01  5.80924857e-01  2.80126297e+00]
 [ 3.76373719e-01  2.91042875e-01  3.04980674e+00]
 [ 4.44023743e-01  4.42314868e-01  3.62675111e+00]
 [ 6.36648569e-01  2.70430722e-01  2.66781270e+00]
 [ 7.52659692e-01  7.64470849e-01  2.53365761e+00]
 [ 7.44977396e-02  6.81705689e-01  4.18331260e+00]
 [ 3.399238