In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [3]:
#load file 
df = pd.read_csv('response indo.csv')
df

Age (umur) Occupation (Pekerjaan)  Music  Slow songs or fast songs  Dance  \
0           19              Mahasiswa      3                         3      1   
1           19              Mahasiswa      5                         3      5   
2           20              Mahasiswa      5                         2      1   
3           19              Mahasiswa      5                         2      3   
4           19              Mahasiswa      5                         3      4   
..         ...                    ...    ...                       ...    ...   
70          20              Mahasiswa      5                         3      4   
71          20              Mahasiswa      5                         3      2   
72          20              Mahasiswa      4                         4      2   
73          21              Mahasiswa      5                         3      5   
74          19              Mahasiswa      5                         3      4   

    Folk  Country  Classical music  Musical  Pop  ...  Reggae, Ska  \
0      1        1                1        4    5  ...            1   
1      4        4                4        5    4  ...            4   
2      2        1                5        5    4  ...            1   
3      3        4                4        4    4  ...            2   
4      4        3                3        3    4  ...            3   
..   ...      ...              ...      ...  ...  ...          ...   
70     3        4                2        3    4  ...            1   
71     2        3                2        3    5  ...            3   
72     1        1                3        2    4  ...            1   
73     3        3                3        3    4  ...            3   
74     2        2                3        3    4  ...            1   

    Swing, Jazz  Rock n roll  Alternative  Latino  Techno, Trance  Opera  \
0             4            1            1       1               1      1   
1             5            5            5       4               5      4   
2             3            1            1       1               1      3   
3             5            3            3       4               3      3   
4             4            3            3       3               3      3   
..          ...          ...          ...     ...             ...    ...   
70            3            3            2       1               1      2   
71            4            3            3       4               4      4   
72            5            1            2       1               5      1   
73            3            3            5       2               4      2   
74            2            3            4       1               2      2   

           Smoking         Alcohol  Healthy eating  
0     never smoked           never               2  
1   current smoker           never               2  
2     never smoked  social drinker               5  
3     never smoked           never               4  
4     never smoked           never               4  
..             ...             ...             ...  
70    never smoked  social drinker               3  
71    never smoked           never               3  
72    never smoked  social drinker               4  
73    never smoked  social drinker               1  
74    never smoked  social drinker               3  

[75 rows x 24 columns]

In [4]:
#mengubah string menjadi angka di Smoking  
df["Smoking"] = df["Smoking"].replace('current smoker', 3)  
df["Smoking"] = df["Smoking"].replace('former smoker', 2) 
df["Smoking"] = df["Smoking"].replace('tried smoking', 1)   
df["Smoking"] = df["Smoking"].replace('never smoked', 0)
#mengubah string menjadi angka di Alcohol
df["Alcohol"] = df["Alcohol"].replace('drink a lot', 2)  
df["Alcohol"] = df["Alcohol"].replace('social drinker', 1)    
df["Alcohol"] = df["Alcohol"].replace('never', 0)

In [5]:
#drop data
newDf = df.dropna()
print(newDf.isna().values.any())

False


In [6]:
#declare dataset feature and target 
feature = newDf[["Music","Slow songs or fast songs","Dance","Folk","Country","Classical music","Musical","Pop","Rock","Metal or Hardrock","Punk","Hiphop, Rap","Reggae, Ska","Swing, Jazz","Rock n roll","Alternative","Latino","Techno, Trance","Opera"]]
target = newDf[["Smoking","Alcohol","Healthy eating"]]
x, y = np.array(feature), np.array(target)

In [7]:
#mengapply PolynominalFeatures untuk selanjutnya dimasukkan ke linear regression
transformer = PolynomialFeatures(degree=2, include_bias=False)

In [8]:
#mengfit data
transformer.fit(x)

PolynomialFeatures(degree=2, include_bias=False, interaction_only=False,
                   order='C')

In [9]:
#mengtransform input array 
x= transformer.transform(x)

In [10]:
print(x)

[[ 3.  3.  1. ...  1.  1.  1.]
 [ 5.  3.  5. ... 25. 20. 16.]
 [ 5.  2.  1. ...  1.  3.  9.]
 ...
 [ 4.  4.  2. ... 25.  5.  1.]
 [ 5.  3.  5. ... 16.  8.  4.]
 [ 5.  3.  4. ...  4.  4.  4.]]


In [11]:
#mengapply linear regression dan fit
model = LinearRegression().fit(x, y)

In [14]:
r_sq = model.score(x, y)
print('coefficient of determination:', r_sq)# hasil R-Squared (bila di bawah 0.5 maka feature tidak berpengaruh kepada target)
print('intercept:', model.intercept_)# hasil coefficient pada b0 (bila di atas 0.05 maka feature tidak berpengaruh kepada target)
print('slope:', model.coef_)# hasil coefficient pada bias setelah b0 yakni b1 b2 b3(bila di atas 0.05 maka feature tidak berpengaruh kepada target)

coefficient of determination: 1.0
intercept: [ 0.05672771 -0.19318576  0.25670976]
slope: [[-4.96436302e-03  1.69925027e-02  1.31255724e-03 -4.27014677e-02
  -1.62620487e-02 -1.68539217e-02 -2.99780510e-02  3.28871071e-04
  -2.46300375e-03  1.33152833e-02  7.96408297e-04 -4.67943798e-03
  -9.84563068e-03  9.52804680e-03 -1.34609340e-02 -2.29685040e-02
  -1.55358216e-03 -4.74088089e-03 -1.06797798e-02 -3.06710014e-02
   1.89809290e-02 -1.64534939e-01  2.77076330e-02  7.22780634e-03
   5.67462072e-02  5.23425014e-02  9.32575713e-02 -7.76947345e-02
  -3.75679684e-02  4.31437126e-02  2.20504181e-02  1.14861565e-01
   1.82849192e-02 -4.57234939e-02 -8.17082665e-02  5.59769460e-03
   1.08011049e-02  8.48612172e-02  1.23542747e-01  9.43940172e-02
  -1.19604231e-01  3.44532679e-02 -7.94475477e-02 -1.05331372e-01
   7.64856954e-02  1.34125171e-01  3.66030710e-02 -5.39431357e-02
  -1.56778012e-02 -8.73257169e-02  3.00638930e-02  8.61165045e-05
   2.71493277e-03 -5.67867109e-02 -6.38494579e-02 -1

C:\Users\Albert\Anaconda3\lib\site-packages\sklearn\base.py:420: FutureWarning: The default value of multioutput (not exposed in score method) will change from 'variance_weighted' to 'uniform_average' in 0.23 to keep consistent with 'metrics.r2_score'. To specify the default value manually and avoid the warning, please either call 'metrics.r2_score' directly or make a custom scorer with 'metrics.make_scorer' (the built-in scorer 'r2' uses multioutput='uniform_average').
  "multioutput='uniform_average').", FutureWarning)


In [13]:
y_pred = model.predict(x)
print('predicted response:', y_pred, sep='\n')
#menghasilkan prediksi prediksi target dengan linear regression

predicted response:
[[ 1.94289029e-15  3.44169138e-15  2.00000000e+00]
 [ 3.00000000e+00 -4.55191440e-15  2.00000000e+00]
 [ 1.94289029e-15  1.00000000e+00  5.00000000e+00]
 [ 6.10622664e-16 -1.44328993e-15  4.00000000e+00]
 [ 6.10622664e-16  4.77395901e-15  4.00000000e+00]
 [-6.05071548e-15  1.22124533e-15  4.00000000e+00]
 [-3.16413562e-15 -3.77475828e-15  1.00000000e+00]
 [ 1.49880108e-15  4.32986980e-15  5.00000000e+00]
 [ 6.10622664e-16  1.22124533e-15  3.00000000e+00]
 [-1.16573418e-15  2.00000000e+00  3.00000000e+00]
 [ 1.66533454e-16 -2.77555756e-15  2.00000000e+00]
 [ 6.10622664e-16  1.00000000e+00  4.00000000e+00]
 [-1.60982339e-15  1.00000000e+00  4.00000000e+00]
 [-1.60982339e-15  5.55111512e-16  2.00000000e+00]
 [-3.83026943e-15 -1.11022302e-16  3.00000000e+00]
 [-2.94209102e-15 -1.44328993e-15  4.00000000e+00]
 [ 1.00000000e+00  1.00000000e+00  3.00000000e+00]
 [-2.49800181e-15  1.00000000e+00  3.00000000e+00]
 [-4.71844785e-15  1.00000000e+00  4.00000000e+00]
 [ 1.000000