In [1]:
import pandas as pd
import numpy as np
import statsmodels.api as sm

In [2]:
#load file 
df = pd.read_csv('responses.csv')
df

Music  Slow songs or fast songs  Dance  Folk  Country  Classical music  \
0       5.0                       3.0    2.0   1.0      2.0              2.0   
1       4.0                       4.0    2.0   1.0      1.0              1.0   
2       5.0                       5.0    2.0   2.0      3.0              4.0   
3       5.0                       3.0    2.0   1.0      1.0              1.0   
4       5.0                       3.0    4.0   3.0      2.0              4.0   
...     ...                       ...    ...   ...      ...              ...   
1005    5.0                       2.0    5.0   2.0      2.0              5.0   
1006    4.0                       4.0    5.0   1.0      3.0              4.0   
1007    4.0                       3.0    1.0   1.0      2.0              2.0   
1008    5.0                       3.0    3.0   3.0      1.0              3.0   
1009    5.0                       5.0    4.0   3.0      2.0              3.0   

      Musical  Pop  Rock  Metal or Hardrock  ...   Age  Height  Weight  \
0         1.0  5.0   5.0                1.0  ...  20.0   163.0    48.0   
1         2.0  3.0   5.0                4.0  ...  19.0   163.0    58.0   
2         5.0  3.0   5.0                3.0  ...  20.0   176.0    67.0   
3         1.0  2.0   2.0                1.0  ...  22.0   172.0    59.0   
4         3.0  5.0   3.0                1.0  ...  20.0   170.0    59.0   
...       ...  ...   ...                ...  ...   ...     ...     ...   
1005      4.0  4.0   4.0                3.0  ...  20.0   164.0    57.0   
1006      1.0  4.0   1.0                1.0  ...  27.0   183.0    80.0   
1007      2.0  3.0   4.0                1.0  ...  18.0   173.0    75.0   
1008      1.0  3.0   4.0                1.0  ...  25.0   173.0    58.0   
1009      3.0  4.0   1.0                1.0  ...  21.0   185.0    72.0   

      Number of siblings  Gender  Left - right handed  \
0                    1.0  female         right handed   
1                    2.0  female         right handed   
2                    2.0  female         right handed   
3                    1.0  female         right handed   
4                    1.0  female         right handed   
...                  ...     ...                  ...   
1005                 1.0  female         right handed   
1006                 5.0    male          left handed   
1007                 0.0  female         right handed   
1008                 1.0  female         right handed   
1009                 1.0    male         right handed   

                    Education  Only child  Village - town  \
0     college/bachelor degree          no         village   
1     college/bachelor degree          no            city   
2            secondary school          no            city   
3     college/bachelor degree         yes            city   
4            secondary school          no         village   
...                       ...         ...             ...   
1005         secondary school          no            city   
1006           masters degree          no         village   
1007         secondary school         yes            city   
1008  college/bachelor degree          no            city   
1009         secondary school          no         village   

      House - block of flats  
0             block of flats  
1             block of flats  
2             block of flats  
3             house/bungalow  
4             house/bungalow  
...                      ...  
1005          house/bungalow  
1006          house/bungalow  
1007          block of flats  
1008          block of flats  
1009          house/bungalow  

[1010 rows x 150 columns]

In [3]:
#mengubah string menjadi angka di Smoking  
df["Smoking"] = df["Smoking"].replace('current smoker', 3)  
df["Smoking"] = df["Smoking"].replace('former smoker', 2) 
df["Smoking"] = df["Smoking"].replace('tried smoking', 1)   
df["Smoking"] = df["Smoking"].replace('never smoked', 0)
#mengubah string menjadi angka di Alcohol
df["Alcohol"] = df["Alcohol"].replace('drink a lot', 2)  
df["Alcohol"] = df["Alcohol"].replace('social drinker', 1)    
df["Alcohol"] = df["Alcohol"].replace('never', 0)

In [4]:
#drop data
newDf = df.dropna()
print(newDf.isna().values.any())

False


In [5]:
#declare dataset feature and target 
feature = newDf[["Music","Slow songs or fast songs","Dance","Folk","Country","Classical music","Musical","Pop","Rock","Metal or Hardrock","Punk","Hiphop, Rap","Reggae, Ska","Swing, Jazz","Rock n roll","Alternative","Latino","Techno, Trance","Opera"]]
target = newDf[["Smoking","Alcohol","Healthy eating"]]
x, y = np.array(feature), np.array(target)

In [6]:
#memasukkan angka 1 di setiap kolom pertama feature
x = sm.add_constant(x)

In [7]:
#print x and y 
print(x)
print(y)

[[1. 5. 3. ... 1. 1. 1.]
 [1. 4. 4. ... 2. 1. 1.]
 [1. 5. 5. ... 5. 1. 3.]
 ...
 [1. 4. 3. ... 1. 1. 1.]
 [1. 5. 3. ... 2. 2. 1.]
 [1. 5. 5. ... 2. 3. 1.]]
[[0. 2. 4.]
 [0. 2. 3.]
 [1. 2. 3.]
 ...
 [1. 1. 2.]
 [1. 1. 3.]
 [1. 1. 3.]]


In [18]:
#memanggil fungsi OLS dari statmodels
model = sm.OLS(y, x)

In [19]:
#model fit untuk mengeluarkan 
r_sq = model.fit()

In [20]:
r_sq = model.score(x, y)
print('coefficient of determination:', r_sq)# hasil R-Squared (bila di bawah 0.5 maka feature tidak berpengaruh kepada target)
print('intercept:', model.intercept_)# hasil coefficient pada b0 (bila di atas 0.05 maka feature tidak berpengaruh kepada target)
print('slope:', model.coef_)# hasil coefficient pada bias setelah b0 yakni b1 b2 b3(bila di atas 0.05 maka feature tidak berpengaruh kepada target)


ValueError: shapes (20,20) and (674,20) not aligned: 20 (dim 1) != 674 (dim 0)